# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp_daemon.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'mcp_daemon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10mcp_daemon.proto\x12\nmcp_daemon\")\n\x12GetAllToolsRequest\x12\x13\n\x0b\x63onfig_path\x18\x01 \x01(\t\"\xae\x01\n\x13GetAllToolsResponse\x12K\n\x0ftools_by_server\x18\x01 \x03(\x0b\x32\x32.mcp_daemon.GetAllToolsResponse.ToolsByServerEntry\x1aJ\n\x12ToolsByServerEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.mcp_daemon.ToolList:\x02\x38\x01\"+\n\x08ToolList\x12\x1f\n\x05tools\x18\x01 \x03(\x0b\x32\x10.mcp_daemon.Tool\"?\n\x04Tool\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cinput_schema\x18\x03 \x01(\t\"a\n\x0f\x43\x61llToolRequest\x12\x13\n\x0b\x63onfig_path\x18\x01 \x01(\t\x12\x13\n\x0bserver_name\x18\x02 \x01(\t\x12\x11\n\ttool_name\x18\x03 \x01(\t\x12\x11\n\targuments\x18\x04 \x01(\t\"B\n\x10\x43\x61llToolResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"2\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\xe3\x01\n\tMcpDaemon\x12N\n\x0bGetAllTools\x12\x1e.mcp_daemon.GetAllToolsRequest\x1a\x1f.mcp_daemon.GetAllToolsResponse\x12\x45\n\x08\x43\x61llTool\x12\x1b.mcp_daemon.CallToolRequest\x1a\x1c.mcp_daemon.CallToolResponse\x12?\n\x06Health\x12\x19.mcp_daemon.HealthRequest\x1a\x1a.mcp_daemon.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_daemon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETALLTOOLSRESPONSE_TOOLSBYSERVERENTRY']._loaded_options = None
  _globals['_GETALLTOOLSRESPONSE_TOOLSBYSERVERENTRY']._serialized_options = b'8\001'
  _globals['_GETALLTOOLSREQUEST']._serialized_start=32
  _globals['_GETALLTOOLSREQUEST']._serialized_end=73
  _globals['_GETALLTOOLSRESPONSE']._serialized_start=76
  _globals['_GETALLTOOLSRESPONSE']._serialized_end=250
  _globals['_GETALLTOOLSRESPONSE_TOOLSBYSERVERENTRY']._serialized_start=176
  _globals['_GETALLTOOLSRESPONSE_TOOLSBYSERVERENTRY']._serialized_end=250
  _globals['_TOOLLIST']._serialized_start=252
  _globals['_TOOLLIST']._serialized_end=295
  _globals['_TOOL']._serialized_start=297
  _globals['_TOOL']._serialized_end=360
  _globals['_CALLTOOLREQUEST']._serialized_start=362
  _globals['_CALLTOOLREQUEST']._serialized_end=459
  _globals['_CALLTOOLRESPONSE']._serialized_start=461
  _globals['_CALLTOOLRESPONSE']._serialized_end=527
  _globals['_HEALTHREQUEST']._serialized_start=529
  _globals['_HEALTHREQUEST']._serialized_end=544
  _globals['_HEALTHRESPONSE']._serialized_start=546
  _globals['_HEALTHRESPONSE']._serialized_end=596
  _globals['_MCPDAEMON']._serialized_start=599
  _globals['_MCPDAEMON']._serialized_end=826
# @@protoc_insertion_point(module_scope)
