# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mcp_daemon_pb2 as mcp__daemon__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mcp_daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class McpDaemonStub(object):
    """The MCP Daemon service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllTools = channel.unary_unary(
                '/mcp_daemon.McpDaemon/GetAllTools',
                request_serializer=mcp__daemon__pb2.GetAllToolsRequest.SerializeToString,
                response_deserializer=mcp__daemon__pb2.GetAllToolsResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/mcp_daemon.McpDaemon/CallTool',
                request_serializer=mcp__daemon__pb2.CallToolRequest.SerializeToString,
                response_deserializer=mcp__daemon__pb2.CallToolResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/mcp_daemon.McpDaemon/Health',
                request_serializer=mcp__daemon__pb2.HealthRequest.SerializeToString,
                response_deserializer=mcp__daemon__pb2.HealthResponse.FromString,
                _registered_method=True)


class McpDaemonServicer(object):
    """The MCP Daemon service
    """

    def GetAllTools(self, request, context):
        """Get all available tools from all MCP servers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Call a specific tool on a specific server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check to verify daemon is running
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_McpDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllTools': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTools,
                    request_deserializer=mcp__daemon__pb2.GetAllToolsRequest.FromString,
                    response_serializer=mcp__daemon__pb2.GetAllToolsResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=mcp__daemon__pb2.CallToolRequest.FromString,
                    response_serializer=mcp__daemon__pb2.CallToolResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=mcp__daemon__pb2.HealthRequest.FromString,
                    response_serializer=mcp__daemon__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp_daemon.McpDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp_daemon.McpDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class McpDaemon(object):
    """The MCP Daemon service
    """

    @staticmethod
    def GetAllTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp_daemon.McpDaemon/GetAllTools',
            mcp__daemon__pb2.GetAllToolsRequest.SerializeToString,
            mcp__daemon__pb2.GetAllToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp_daemon.McpDaemon/CallTool',
            mcp__daemon__pb2.CallToolRequest.SerializeToString,
            mcp__daemon__pb2.CallToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp_daemon.McpDaemon/Health',
            mcp__daemon__pb2.HealthRequest.SerializeToString,
            mcp__daemon__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
