name: Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python 3.9 is not supported by MCP Python SDK
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Install dependencies
      run: |
        pip install -e '.[test]'
    - name: Sync dependencies
      run: |
        uv sync --all-extras
    - name: Check (lint)
      run: |
        ./check.sh
    - name: Run tests
      run: |
        python -m pytest
    - name: Run online tests
      run: |
        python -m pytest -m "online"
    - name: Run e2e tests
      run: |
        ./e2e/e2e.sh
